<?php
/**
 * Created by PhpStorm.
 * User: Ahmad Adlouni
 * Date: 3/14/2018
 * Time: 10:10 AM
 */

namespace App\Form\Type;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class DeviceScheduleType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

}